apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: sock-shop
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: sock-shop-orders
    app.kubernetes.io/version: "1.0"
    helm.sh/chart: sock-shop-0.2.0
  name: sock-shop-orders
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: sock-shop
      app.kubernetes.io/name: sock-shop-orders
  template:
    metadata:
      annotations:
        prometheus.io/port: "80"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/instance: sock-shop
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: sock-shop-orders
        app.kubernetes.io/version: "1.0"
        helm.sh/chart: sock-shop-0.2.0
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Xms64m -Xmx350m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC
            -Djava.security.egd=file:/dev/urandom
        image: sysdigtraining/orders:0.4.7
        imagePullPolicy: Always
        name: orders
        ports:
        - containerPort: 80
          protocol: TCP
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
          privileged: true
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
