name: Simulate CVE-2025-30066

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

jobs:
  simulate-attack:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run malicious action
        uses: ./
